FloodLevels/Controllers/StationController.cs
using FloodLevels.Data.Model;
using FloodLevels.Data;
using Microsoft.AspNetCore.Mvc;



namespace FloodLevels.Controllers
{
    [ApiController]
    [Route("api/")]
    public class StationController : Controller
    {
        public IActionResult StationOverview()
        {
            return View();
        }

        private ApplicationDbContext _context { get; set; }

        public StationController(ApplicationDbContext context)
        {
            _context = context;
        }
        [HttpGet]
        [Route("get-stations")]
        public IActionResult GetListOfStations()
        {
            var list = _context.Stations.ToList();
            return StatusCode(200, new JsonResult(list));
        }
        [HttpPost]
        [Route("add-station")]
        public IActionResult AddStation(Station Station)
        {
            if (_context.Stations.Where(x => x.Title.Equals(Station.Title)).Any())
            {
                return StatusCode(400,
                    new JsonResult("Duplicities are not allowed."));
            }
            _context.Stations.Add(Station);
            _context.SaveChanges();

            return StatusCode(200,
                new JsonResult("Station has been successfully added"));

        }

        
    }
}

FloodLevels/Pages/StationPages/CreateStation.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using FloodLevels.Data;
using FloodLevels.Data.Model;

namespace FloodLevels.Pages.StationPages
{
    public class CreateStationModel : PageModel
    {

        [BindProperty]
        public Station Station { get; set; }

        private ApplicationDbContext _context;
        public CreateStationModel(ApplicationDbContext context)
        {
            Station = new Station();
            _context = context;
        }
        public IActionResult OnPost()
        {
            if (_context.Stations.Any(s => s.Title == Station.Title))
            {
                return Content("<script>alert('This station already exists.');window.history.back();</script>", "text/html");
            }

            _context.Stations.Add(Station);
            _context.SaveChanges();

            return RedirectToPage("./Stations");
        }


        public void OnGet()
        {
        }
    }
}

FloodLevels/Pages/StationPages/Detail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using FloodLevels.Data;
using FloodLevels.Data.Model;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;

namespace FloodLevels.Pages.StationPages
{
    public class DetailModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<DetailModel> _logger;
        public DetailModel(ApplicationDbContext context, ILogger<DetailModel> logger)
        {
            _context = context;
            _logger = logger;
        }

        [BindProperty]
        public Station Station { get; set; }

        [BindProperty]
        public bool IsEditMode { get; set; }
        public List<Values> StationValues { get; set; }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            Station = await _context.Stations.FindAsync(id);

            if (Station == null)
            {
                return NotFound();
            }

            StationValues = await _context.Values
                .Where(v => v.StationId == id)
                .OrderByDescending(v => v.Timestamp)
                .ToListAsync();

            IsEditMode = false;

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            

            var stationToUpdate = await _context.Stations.FindAsync(Station.Id);

            if (stationToUpdate == null)
            {
                return NotFound();
            }

            stationToUpdate.Title = Station.Title;
            stationToUpdate.FloodLevel = Station.FloodLevel;
            stationToUpdate.DroughtLevel = Station.DroughtLevel;
            stationToUpdate.TimeOutinMinutes = Station.TimeOutinMinutes;

            if (_context.Stations.Any(s => s.Title == Station.Title && s.Id != Station.Id))
            {
                return Content("<script>alert('This station already exists.');window.history.back();</script>", "text/html");
            }

            if (stationToUpdate.DroughtLevel >= stationToUpdate.FloodLevel)
            {
                return Content("<script>alert('Flood level must be higher than Drought level');window.history.back();</script>", "text/html");
            }

            await _context.SaveChangesAsync();

            IsEditMode = false;
            return RedirectToPage("./Detail", new { id = Station.Id });

        }

        public async Task<IActionResult> OnPostEditAsync(int id)
        {
            Station = await _context.Stations.FindAsync(id);

            if (Station == null)
            {
                return NotFound();
            }

            IsEditMode = true;
            
            return Page();
        }

        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {
            var stationToDelete = await _context.Stations.FindAsync(id);

            if (stationToDelete == null)
            {
                return NotFound();
            }

            var valuesToDelete = await _context.Values.Where(v => v.StationId == id).ToListAsync();
            _context.Values.RemoveRange(valuesToDelete);
            _context.Stations.Remove(stationToDelete);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Stations");
        }
    }
}

FloodLevels/Pages/StationPages/Stations.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Data.SqlClient;
using FloodLevels.Data.Model;
using Microsoft.EntityFrameworkCore;
using FloodLevels.Data;
using System.Linq;
using System.Collections.Generic;


namespace FloodLevels.Pages.StationPages
{
    public class StationsModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        public StationsModel(ApplicationDbContext context)
        {
            _context = context;
        }
        
        public List<StationInfo> Stations = new List<StationInfo>();
        public void OnGet()
        {
            try
            {
                string connectionString = "Server=(localdb)\\mssqllocaldb;Database=FloodLevels;Trusted_Connection=True;MultipleActiveResultSets=true";
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    string sql = "SELECT * FROM Stations";
                   
                    using (SqlCommand command = new SqlCommand(sql, connection)) 
                    {
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                StationInfo station = new StationInfo();
                                station.Id = reader.GetInt32(0);
                                station.Title = reader.GetString(1);
                                station.FloodLevel = reader.GetInt32(2);
                                station.DroughtLevel = reader.GetInt32(3);
                                station.TimeOutinMinutes = reader.GetInt32(4);

                                Stations.Add(station);
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {

            }
        }

        public class StationInfo
        {
            [Key]
            public int Id { get; set; }

            public string Title { get; set; }

            public int FloodLevel { get; set; }

            public int DroughtLevel { get; set; }

            public int TimeOutinMinutes { get; set; }
        }
    }
}

FloodLevels/Pages/StationPages/ValuesOverview.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using FloodLevels.Data.Model;
using System.Data.SqlClient;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;

namespace FloodLevels.Pages.StationPages
{
    public class ValuesOverviewModel : PageModel
    {
        public List<ValueInfo> Values = new List<ValueInfo>();
        [BindProperty(SupportsGet = true)]
        public string Filter { get; set; }
        public void OnGet()
        {
            try
            {
                string connectionString = "Server=(localdb)\\mssqllocaldb;Database=FloodLevels;Trusted_Connection=True;MultipleActiveResultSets=true";
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    string sql = @"
                                    SELECT 
                                        V.Id, 
                                        V.Value, 
                                        V.Timestamp, 
                                        S.Title AS StationTitle,
                                        S.FloodLevel,
                                        S.DroughtLevel
                                    FROM 
                                        [Values] V
                                    INNER JOIN 
                                        Stations S 
                                    ON 
                                        V.StationId = S.Id";

                    if (!string.IsNullOrEmpty(Filter))
                    {
                        sql += " WHERE S.Title LIKE @Filter";
                    }
                    using (SqlCommand command = new SqlCommand(sql, connection))
                    {
                        if (!string.IsNullOrEmpty(Filter))
                        {
                            command.Parameters.AddWithValue("@Filter", $"%{Filter}%");
                        }
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            Values = new List<ValueInfo>();
                            while (reader.Read())
                            {
                                ValueInfo newValue = new ValueInfo();
                                newValue.Id = reader.GetInt32(0);
                                newValue.Value = reader.GetInt32(1);
                                newValue.Timestamp = reader.GetDateTime(2);
                                newValue.StationTitle = reader.GetString(3);
                                newValue.FloodLevel = reader.GetInt32(4);
                                newValue.DroughtLevel = reader.GetInt32(5);
                                Values.Add(newValue);
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Chyba: {ex.Message}");
            }
        }
    }

    public class ValueInfo
    {
        public int Id { get; set; }
        public int Value { get; set; }
        public DateTime Timestamp { get; set; }
        public string StationTitle { get; set; }
        public int FloodLevel { get; set; }
        public int DroughtLevel { get; set; }
    }
}

FloodLevels/Pages/StationPages/CreateStation.cshtml
@page
@model FloodLevels.Pages.StationPages.CreateStationModel
@{
}

<h1>New Station</h1>
<hr />

<form id="createForm" method="post">

    <div class="form-group">
        <label asp-for="Station.Title" class="control-label"></label>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="fa fa-pencil-alt"></i></span>
            </div>
            <input asp-for="Station.Title" class="form-control form-control-sm" maxlength="16" style="max-width: 300px;" />
        </div>
        <small class="form-text text-muted">Title should not exceed 16 characters.</small>
        <span asp-validation-for="Station.Title" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Station.FloodLevel" class="control-label"></label>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="fa fa-water"></i></span>
            </div>
            <input asp-for="Station.FloodLevel" class="form-control form-control-sm" min="1" max="100" style="max-width: 300px;" />
        </div>
        <small class="form-text text-muted">Flood level must be between 1 and 100.</small>
        <span asp-validation-for="Station.FloodLevel" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Station.DroughtLevel" class="control-label"></label>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="fa fa-sun"></i></span>
            </div>
            <input asp-for="Station.DroughtLevel" class="form-control form-control-sm" min="1" max="100" style="max-width: 300px;" />
        </div>
        <small class="form-text text-muted">Drought level must be between 1 and 100.</small>
        <span asp-validation-for="Station.DroughtLevel" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Station.TimeOutinMinutes" class="control-label"></label>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="fa fa-clock"></i></span>
            </div>
            <input asp-for="Station.TimeOutinMinutes" class="form-control form-control-sm" style="max-width: 300px;" />
        </div>
        <small class="form-text text-muted">Specify the timeout in minutes.</small>
        <span asp-validation-for="Station.TimeOutinMinutes" class="text-danger"></span>
    </div>

    <button class="btn btn-primary btn-lg mt-3" type="submit">Send</button>

</form>

<script>
    var floodLevelInput = document.getElementById('Station_FloodLevel');
    var droughtLevelInput = document.getElementById('Station_DroughtLevel');

    floodLevelInput.addEventListener('input', validateLevels);
    droughtLevelInput.addEventListener('input', validateLevels);

    function validateLevels() {
        var floodLevel = parseInt(floodLevelInput.value);
        var droughtLevel = parseInt(droughtLevelInput.value);

        if (floodLevel <= droughtLevel) {
            droughtLevelInput.setCustomValidity('Flood level must be higher than drought level.');
        } else {
            droughtLevelInput.setCustomValidity('');
        }
    }
</script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />

<style>
    .form-group {
        margin-bottom: 1.5rem;
    }

    .input-group-text {
        background-color: #f8f9fa;
    }
</style>

FloodLevels/Pages/StationPages/Detail.cshtml
@page "{id:int}"
@model FloodLevels.Pages.StationPages.DetailModel
@{
    ViewData["Title"] = "Station Detail";
    var isEditMode = Model.IsEditMode;
}

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-annotation@1.0.2"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns"></script>



@if (isEditMode)
{
    <form id="editForm" method="post">

        <input type="hidden" asp-for="Station.Id" />
        <div class="form-group">
            <label asp-for="Station.Title" class="control-label"></label>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-pencil-alt"></i></span>
                </div>
                <input asp-for="Station.Title" class="form-control form-control-sm" maxlength="16" style="max-width: 300px;" />
            </div>
            <small class="form-text text-muted">Title should not exceed 16 characters.</small>
            <span asp-validation-for="Station.Title" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Station.FloodLevel" class="control-label"></label>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-water"></i></span>
                </div>
                <input asp-for="Station.FloodLevel" id="Station_FloodLevel" class="form-control form-control-sm" min="1" max="100" style="max-width: 300px;" />
            </div>
            <small class="form-text text-muted">Flood level must be between 1 and 100.</small>
            <span asp-validation-for="Station.FloodLevel" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Station.DroughtLevel" class="control-label"></label>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-sun"></i></span>
                </div>
                <input asp-for="Station.DroughtLevel" id="Station_DroughtLevel" class="form-control form-control-sm" min="1" max="100" style="max-width: 300px;" />
            </div>
            <small class="form-text text-muted">Drought level must be between 1 and 100.</small>
            <span asp-validation-for="Station.DroughtLevel" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Station.TimeOutinMinutes" class="control-label"></label>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-clock"></i></span>
                </div>
                <input asp-for="Station.TimeOutinMinutes" class="form-control form-control-sm" style="max-width: 300px;" />
            </div>
            <span asp-validation-for="Station.TimeOutinMinutes" class="text-danger"></span>
        </div>
       
        <button type="submit" class="btn btn-primary" asp-page-handler="Save">Save</button>

    </form>
}
else
{
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 mx-auto">
                <table class="table table-bordered">
                    <thead class="thead-dark">
                        <tr>
                            <th>
                                <div class="d-flex justify-content-between align-items-center">
                                    <span>@Model.Station.Title</span>
                                    <div class="station-actions">
                                        <form method="post" asp-page-handler="Edit" class="d-inline">
                                            <button type="submit" class="btn btn-outline-primary mr-2"><i class="bi bi-pencil"></i></button>
                                        </form>
                                        <form method="post" asp-page-handler="Delete" class="d-inline">
                                            <button type="submit" class="btn btn-outline-danger"><i class="bi bi-trash"></i></button>
                                        </form>
                                    </div>
                                </div>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><strong>Flood Level:</strong> @Model.Station.FloodLevel</td>
                        </tr>
                        <tr>
                            <td><strong>Drought Level:</strong> @Model.Station.DroughtLevel</td>
                        </tr>
                        <tr>
                            <td><strong>Timeout in Minutes:</strong> @Model.Station.TimeOutinMinutes</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>


    @if (Model.StationValues != null && Model.StationValues.Any())
    {
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <h3>Station History:</h3>
                    <div style="overflow-x:auto;">
                        <table class="table table-bordered table-hover table-striped">
                            <thead class="thead-dark">
                                <tr>
                                    <th>Value</th>
                                    <th>Timestamp</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var value in Model.StationValues)
                                {
                                    var cssClass = (value.Value < Model.Station.DroughtLevel || value.Value > Model.Station.FloodLevel) ? "table-danger" : "";
                                    <tr class="@cssClass">
                                        <td>@value.Value</td>
                                        <td>@value.Timestamp.ToString("yyyy-MM-dd HH:mm:ss")</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-md-9">
                    <canvas id="histogram"></canvas>
                </div>
            </div>
        </div>
    }
    else
    {
        <p>No records available for this station.</p>
    }

    <script>
        document.addEventListener('DOMContentLoaded', function () {           

            var ctx = document.getElementById('histogram').getContext('2d');
            var values = @Html.Raw(Json.Serialize(Model.StationValues.OrderByDescending(v => v.Timestamp).Take(10).Select(v => v.Value)));
            var timestamps = @Html.Raw(Json.Serialize(Model.StationValues.OrderByDescending(v => v.Timestamp).Take(10).Select(v => v.Timestamp)));
            var dates = timestamps.map(timestamp => new Date(timestamp)).reverse(); // Reverse the order of dates

            var floodLevel = @Model.Station.FloodLevel;
            var droughtLevel = @Model.Station.DroughtLevel;

            var chart = new Chart(ctx, {
                type: 'line',
                data: {
                    labels: dates.map(date => date.toLocaleString()),
                    datasets: [{
                        label: 'Water Level',
                        data: values.reverse(),
                        backgroundColor: 'rgba(54, 162, 235, 0.2)',
                        borderColor: 'rgba(54, 162, 235, 1)',
                        borderWidth: 2
                    }]
                },
                options: {
                    scales: {
                        y: {
                            beginAtZero: true
                        }
                    },
                    plugins: {
                        annotation: {
                            annotations: [
                                {
                                    type: 'line',
                                    mode: 'horizontal',
                                    scaleID: 'y',
                                    value: floodLevel,
                                    borderColor: 'rgba(255, 99, 132, 1)',
                                    borderWidth: 2,
                                },
                                {
                                    type: 'line',
                                    mode: 'horizontal',
                                    scaleID: 'y',
                                    value: droughtLevel,
                                    borderColor: 'rgba(255, 99, 132, 1)',
                                    borderWidth: 2,
                                }
                            ]
                        }
                    }
                }
            });
        });       
    </script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" rel="stylesheet">

    <style>
        .table-danger {
            background-color: darkmagenta;
        }

        .table-hover tbody tr:hover {
            background-color: #f1f1f1;
        }

        .table-striped tbody tr:nth-of-type(odd) {
            background-color: #f9f9f9;
        }

        .thead-dark th {
            background-color: #343a40;
            color: #fff;
        }

        .form-group {
            margin-bottom: 1.5rem;
        }

        .input-group-text {
            background-color: #f8f9fa;
        }

        .container {
            background-color: #ffffff;
            border-radius: 10px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
            padding: 20px;
            margin-top: 20px;
        }

        .station-details {
            border: 1px solid #ccc;
            border-radius: 10px;
            padding: 20px;
            margin-bottom: 20px;
            background-color: #f9f9f9;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .station-info p {
            margin: 5px 0;
            color: #333;
        }

        .station-actions {
            text-align: right;
        }

            .station-actions button {
                margin-left: 10px;
            }

    </style>
}

FloodLevels/Pages/StationPages/Stations.cshtml
@page
@model FloodLevels.Pages.StationPages.StationsModel
@{
    ViewData["Title"] = "Display Data";
    string[] StationProperties = new string[]
    {
        "Id",
        "Title",
        "Flood Level",
        "Drought Level",
        "Timeout in Minutes"
    };
}

<h1 class="mb-4">Stations</h1>

<div class="table-responsive">
    <table id="stationsTable" class="table table-bordered table-hover table-striped">
        <thead class="thead-dark">
            <tr>
                @{
                    foreach (var head in StationProperties)
                    {
                        <th>@head</th>
                    }
                }
            </tr>
        </thead>
        <tbody>
            @foreach (var station in Model.Stations)
            {
                <tr onclick="editStation('@station.Id')">
                    <td>@station.Id</td>
                    <td><span style="cursor: pointer; font-weight: bold;">@station.Title</span></td>
                    <td>@station.FloodLevel</td>
                    <td>@station.DroughtLevel</td>
                    <td>@station.TimeOutinMinutes</td>
                </tr>
            }
        </tbody>
    </table>
    <a asp-page="./CreateStation" class="btn btn-success">Add Station</a>
</div>

<script>
    function editStation(stationId) {
        window.location.href = './Detail/' + stationId;
    }
</script>

<style>
    .table-hover tbody tr:hover {
        background-color: #f1f1f1;
    }

    .table-striped tbody tr:nth-of-type(odd) {
        background-color: #f9f9f9;
    }

    .thead-dark th {
        background-color: #343a40;
        color: #fff;
    }
</style>

FloodLevels/Pages/StationPages/ValuesOverview.cshtml
@page
@model FloodLevels.Pages.StationPages.ValuesOverviewModel
@{
    ViewData["Title"] = "Display Data";
    string[] ValueProperties = new string[]
    {
      "Station",
      "Value",
      "Timestamp"
    };

    Model.Values = Model.Values.OrderByDescending(v => v.Timestamp).ToList();
}

<h1 class="mb-4">Records</h1>

<form method="get" class="form-inline mb-3">
    <div class="form-group col-sm-4">
        <label for="filter" class="mr-2">Filter by Station:</label>
        <input type="text" id="filter" name="Filter" value="@Model.Filter" class="form-control" />
    </div>
    <br>
    <div class="col-sm-8">
        <button type="submit" class="btn btn-primary">Search</button>
    </div>
</form>

<div class="table-responsive">
    <table class="table table-bordered table-hover table-striped">
        <thead class="thead-dark">
            <tr>
                @foreach (var head in ValueProperties)
                {
                    <th>@head</th>
                }
            </tr>
        </thead>

        <tbody>
            @foreach (var newValue in Model.Values)
            {
                var cssClass = (newValue.Value < newValue.DroughtLevel || newValue.Value > newValue.FloodLevel) ? "table-danger" : "";
                <tr class="@cssClass">
                    <td>@newValue.StationTitle</td>
                    <td>@newValue.Value</td>
                    <td>@newValue.Timestamp</td>
                </tr>
            }
        </tbody>
    </table>
</div>

<style>
    .table-danger {
        background-color: darkmagenta;
    }

    .table-hover tbody tr:hover {
        background-color: #f1f1f1;
    }

    .table-striped tbody tr:nth-of-type(odd) {
        background-color: #f9f9f9;
    }

    .thead-dark th {
        background-color: #343a40;
        color: #fff;
    }
</style>